sweet: Makefile: undefined reference stpcpy *use Proton-Clang 12 / Clang 12
aarch64-linux-gnu-ld: drivers/built-in.o: in function `devspec_show':
pci-sysfs.c:(.text+0x2fd48): undefined reference to `stpcpy'
aarch64-linux-gnu-ld: drivers/built-in.o: in function `alloc_tty_struct':
(.text+0x200888): undefined reference to `stpcpy'
aarch64-linux-gnu-ld: drivers/built-in.o: in function `tty_register_device_attr':
(.text+0x202be8): undefined reference to `stpcpy'
aarch64-linux-gnu-ld: drivers/built-in.o: in function `show_cons_active':
tty_io.c:(.text+0x2042b4): undefined reference to `stpcpy'

Signed-off-by: wimbiyoas <wyoashizkia@gmail.com>
(cherry picked from commit eaca45d538175a23b33c5e214da1ab83636e6ce7)
Signed-off-by: dopaemon <polarisdp@gmail.com>